app/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app.main.func import Navigation
from app.models import Genre, Room
from app import db

main = Blueprint('main', __name__)
navig = Navigation(db)
genres = Genre.query.all()
games = []          # СОМНИТЕЛЬНОЕ РЕШЕНИЕ С ГЛОБАЛЬНЫМИ ПЕРЕМЕННЫМИ!!!
rooms = []


@main.route("/home")
@login_required
def home():
    try:
        s = request.args.get('s')
        if s:
            global rooms
            rooms = Room.query.filter(Room.name.contains(s)).all()
        else:
            rooms = Room.query.all()
        return render_template("main page.html", rooms=rooms, games=games, genres=genres)
    except Exception as e:
        print(e)


@main.route("/about")
@login_required
def about():
    render_template("about.html")


@main.route("/roomsbygenre/<int:genre_id>")
@login_required
def get_rooms_by_genre(genre_id):
    try:
        global games, rooms
        games, rooms = navig.get_games_and_rooms_by_genre(genre_id)

        s = request.args.get('s')
        if s:
            rooms = Room.query.filter(Room.name.contains(s)).all()

        return render_template("main page.html", rooms=rooms, games=games, genres=genres)
    except Exception as e:
        print(e)


@main.route("/roomsbygame/<int:game_id>")
@login_required
def get_rooms_by_game(game_id):
    try:
        global rooms
        rooms = navig.get_rooms_by_game(game_id)

        s = request.args.get('s')
        if s:
            rooms = Room.query.filter(Room.name.contains(s)).all()

        return render_template("main page.html", rooms=rooms, games=games, genres=genres)
    except Exception as e:
        print(e)

app/matches/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
from app.matches.func import Editor
from app.matches.forms import *
from app.models import Room, UserRoom
from app import db

matches = Blueprint('matches', __name__)
editor = Editor(db)


@matches.route("/editroom/<int:room_id>", methods=['GET', 'POST'])
@login_required
def edit_match(room_id=0):
    form = RoomForm()
    room = Room.query.get(room_id)
    if form.validate_on_submit():
        if room:
            room.name = form.name.data
            room.max_num_of_player = form.max_num_of_player.data
            room.start_time = form.start_time.data
            room.host_message = form.host_message.data
            room.game = form.game_options.data
            db.session.commit()
        else:
            room_id = editor.create_room(current_user, form.name.data, form.start_time.data,
                               form.max_num_of_player.data, form.game_options.data,
                               form.host_message.data)  # возвращает false если слишком много созданных комнат, добавлю уведомление если фолз, если успею

        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('matches.show_room', room_id=room_id))

    if room:
        form.name.data = room.name
        form.max_num_of_player.data = room.max_num_of_player
        form.start_time.data = room.start_time
        form.game_options.data = room.game
        form.host_message.data = room.host_message

    return render_template('make_match.html', form=form)


@matches.route("/delroom/<int:room_id>")
@login_required
def delete_room(room_id):
    editor.delete_room(current_user, room_id)
    return redirect(url_for('matches.user_page'))


@matches.route("/excludeuser/<int:user_id>/<int:room_id>")
@login_required
def exclude_user(user_id, room_id):
    room = Room.query.get(room_id)
    if current_user.id == room.host.id:
        UserRoom.query.filter_by(user_id=user_id, room_id=room.id).delete()
        db.session.commit()
    return redirect(url_for("matches.show_room", room_id=room.id))


@matches.route("/userpage")
@login_required
def user_page():
    rooms = current_user.rooms
    user_rooms = current_user.user_rooms
    return render_template("usr_page.html", rooms=rooms, user_rooms=user_rooms)


@matches.route("/room/<int:room_id>")
@login_required
def show_room(room_id):
    room = Room.query.get(room_id)
    if room_id:
        return render_template('match_page.html', room=room)
    else:
        return redirect(url_for('matches.user_page'))

app/users/routes.py
from flask import render_template, request, Blueprint, redirect, flash, url_for
from flask_login import login_user, current_user, logout_user, login_required
from app.users.forms import RegistrationForm, LoginForm
from app import app
from app.users.func import Accession
from app.models import *
from flask_admin import Admin
from app.users.admin_view import AdminView, HomeAdminView
from app import models, db

users = Blueprint("users", __name__)
access = Accession(db)

admin = Admin(app, 'App', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(AdminView(models.User, db.session))
admin.add_view(AdminView(models.Room, db.session))
admin.add_view(AdminView(models.Game, db.session))
admin.add_view(AdminView(models.Genre, db.session))


@users.route("/register", methods=['GET', 'POST'])
def register():
    try:
        if current_user.is_authenticated:
            return render_template(url_for("main.home"))
        form = RegistrationForm()
        if form.validate_on_submit():
            if access.registration(form.username.data, form.email.data, form.password.data):
                flash("Ваш Аккаунт был успешно создан!", "success")
                return redirect(url_for("users.login"))
            else:
                flash("Такой пользователь уже существует!", 'danger')
        return render_template("registration.html", form=form)
    except Exception as e:
        print(e)


@users.route('/', methods=['GET', 'POST'])
@users.route("/login", methods=['GET', 'POST'])
def login():
    try:
        if current_user.is_authenticated:
            return redirect(url_for("main.home"))
        form = LoginForm()
        if form.validate_on_submit():
            if access.login(form.username.data, form.password.data):
                return redirect(url_for("main.home"))
            else:
                flash("Неправильный логин или пароль!", 'danger')
        return render_template("authorisation.html", form=form)
    except Exception as e:
        print(e)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))

# checked
@users.route("/userinfo")
@login_required
def user_info():
    rooms, user_rooms = access.get_user_information(current_user)
    return render_template("usr_page.html", rooms=rooms, user_rooms=user_rooms)

# checked
@users.route("/joinroom/<int:room_id>")
@login_required
def join_room(room_id):
    room = Room.query.get(room_id)
    if access.join_room(current_user.id, room):
        return render_template('match_page.html', room=room)
    else:
        return redirect(url_for("main.home"))

# checked
@users.route("/leaveroom/<int:room_id>")
@login_required
def leave_room(room_id):
    if access.leave_room(current_user.id, room_id):
        return redirect(url_for("users.user_info"))
    else:
        return redirect((url_for("main.home")))

app/templates/authorisation.html
<html>
<head>
<meta charset="utf-8">
<title>TNB-syte</title>
<link rel="stylesheet" type="text/css" href="../static/aut_style.css">
</head>
<center><h1>TNB-syte</h1></center>
<body>
<form method="POST" action="">
  {{ form.hidden_tag() }}
  <p align="center">
    <label>Ник:<br></label>

    {% if form.username.errors %}
      {{ form.username() }}
      <div>
      {% for error in form.username.errors %}
        <span>{{ error }}</span>
      {% endfor %}
      </div>
    {% else %}
      {{ form.username() }}
    {% endif %}
  </p>

  <p align="center">
    <label>Пароль:<br></label>
    {% if form.password.errors %}
      {{ form.password() }}
      <div>
      {% for error in form.password.errors %}
        <span>{{ error }}</span>
      {% endfor %}
      </div>
    {% else %}
      {{ form.password() }}
    {% endif %}
  </p>

    <a href="#" class="button2">{{ form.submit(class="button2") }}</a>
    <a href="{{ url_for('users.register') }}" class="button3">Зарегистрироваться</a>
</form>

</body>
</html>

app/templates/change_match.html
<html/>
<head>
<meta charset="utf-8">
<title>TNB-syte</title>
<link rel="stylesheet" type="text/css" href="../static/change_match_style.css">
</head>
<body/>
<center/><h1>Изменение комнаты</center>
  <p align="center">
    <label>Название комнаты:<br></label>
    <input name="name" type="text" size="30" maxlength="30" value ="">
  </p>
  <p align="center">
    <label>Время и дата начала:<br></label>
    <input name="name" type="text" size="30" maxlength="30" value ="">
  </p>
  <p align="center">
    <label>Максимальное количество игроков:<br></label>
    <input name="name" type="text" size="30" maxlength="30" value ="">
  </p>
    <p align="center">
    <label>Сообщение для участников:<br></label>
   <textarea name="comment"></textarea>
  </p>
<h2>Список игроков:</h2>
<h3>Василий</h3>
<a href="#" class="button1">Удалить</a>
<h3>Захар</h3>
<a href="#" class="button1">Удалить</a>
 <a href="#" class="button2">Сохранить</a>
 <a href="#" class="button3">Назад</a>
</body>
</html>

app/templates/main page.html
<html>
<head>
<meta charset="utf-8">
<title>TNB-syte</title>
<link rel="stylesheet" type="text/css" href="../static/main_style.css">
</head>
<body>
<center><h1>TNB-syte</h1></center>
<div>
  <a href="{{ url_for('users.user_info') }}" class="button1">Моя страница</a>
</div>
<div>
  <a href="{{ url_for('users.user_info') }}" class="button6">Моя страница2</a>
</div>
<div>
  {% if current_user.is_authenticated %}
  <a href="{{ url_for('users.logout') }}" class="button3">Выход</a>
  {% endif %}
</div>
<div>
  {% if current_user.is_admin %}
  <a href="/admin" class="button4">Редактор</a>
  {% endif %}
</div>
<form action="" method="get">
  <input name="s" placeholder="Поиск комнаты" type="search" value="{{ request.args.get('s', '') }}">
  <button type="submit"></button>
</form>
<ul class="checkboxes">
  {% for genre in genres %}
  <div>
    <a href="{{ url_for('main.get_rooms_by_genre', genre_id=genre.id) }}" class="button25">{{ genre.name }}</a>
  <div/>
  {% endfor %}
</ul>
<ul class="checkboxes2">
  {% for game in games %}
  <div>
    <a href="{{ url_for('main.get_rooms_by_game', game_id=game.id) }}" class="button25">{{ game.name }}</a>
  </div>
  {% endfor %}
</ul>
<h2>Игры:</h2>
<h3>Жанры:</h3>
{% for room in rooms %}
<div class="box">
  <div class="title">
    {{ room.name }}
  </div>
  <div class="meaning">
    {{ room.game.name }}
  </div>
    <div class="button">
  	<a href="{{ url_for('users.join_room', room_id=room.id) }}" class="button25">Вступить</a>
	</div>
</div>
{% endfor %}
</body>
</html>

app/templates/make_match.html
<html>
<head>
<meta charset="utf-8">
<title>TNB-syte</title>
<link rel="stylesheet" type="text/css" href="../static/make_match_style.css">
</head>
<body/>
<center/><h1>Создание комнаты</h1></center>

<form method="POST" action="">
  {{ form.hidden_tag() }}
  <p align="center">
    <label>Название комнаты:<br></label>

    {% if form.name.errors %}
      {{ form.name() }}
      <div>
      {% for error in form.name.errors %}
        <span>{{ error }}</span>
      {% endfor %}
      </div>
    {% else %}
      {{ form.name() }}
    {% endif %}
  </p>
  <p align="center">
    <label>Игра:<br></label>

    {% if form.game_options.errors %}
      {{ form.game_options() }}
      <div>
      {% for error in form.game_options.errors %}
        <span>{{ error }}</span>
      {% endfor %}
      </div>
    {% else %}
      {{ form.game_options() }}
    {% endif %}
  </p>
  <p align="center">
    <label>Количество игроков:<br></label>
    {% if form.max_num_of_player.errors %}
      {{ form.max_num_of_player() }}
      <div>
      {% for error in form.max_num_of_player.errors %}
        <span>{{ error }}</span>
      {% endfor %}
      </div>
    {% else %}
      {{ form.max_num_of_player() }}
    {% endif %}
  </p>
  <p align="center">
    <label>Время проведения:<br></label>
    {% if form.start_time.errors %}
      {{ form.start_time }}
      <div>
      {% for error in form.start_time.errors %}
        <span>{{ error }}</span>
      {% endfor %}
      </div>
    {% else %}
      {{ form.start_time }}
    {% endif %}
  </p>
    <p align="center">
    <label>Сообщение для участников :<br></label>
    {% if form.host_message.errors %}
      {{ form.host_message() }}
      <div>
      {% for error in form.host_message.errors %}
        <span>{{ error }}</span>
      {% endfor %}
      </div>
    {% else %}
      {{ form.host_message() }}
    {% endif %}
  </p>
 <a href="#" class="button2">{{ form.submit(class="button2") }}</a>
</form>

<!--  <p align="center">-->
<!--    <label>Название комнаты:<br></label>-->
<!--    <input name="name" type="text" size="30" maxlength="30" value ="">-->
<!--  </p>-->
<!--  <p align="center">-->
<!--    <label>Время и дата начала:<br></label>-->
<!--    <input name="name" type="text" size="30" maxlength="30" value ="">-->
<!--  </p>-->
<!--  <p align="center">-->
<!--    <label>Максимальное количество игроков:<br></label>-->
<!--    <input name="name" type="text" size="30" maxlength="30" value ="">-->
<!--  </p>-->
<!--  <p align="center">-->
<!--    <label>Сообщение для участников:<br></label>-->
<!--   <textarea name="comment"></textarea>-->
<!--  </p>-->
<!-- <a href="#" class="button2">Создать</a>-->
 <a href="#" class="button3">Назад</a>
</body>
</html>

app/templates/match_page.html
<html/>
<head>
<meta charset="utf-8">
<title>TNB-syte</title>
<link rel="stylesheet" type="text/css" href="../static/match_page_style.css">
</head>
<body/>
<center/><h1>{{ room.name }}</h1></center>
  <p align="center">
    <label>Дата проведения: {{ room.start_time.date() }}<br></label>
  </p>
  <p align="center">
    <label>Максимальное количество игроков: {{ room.max_num_of_player }}<br></label>
  </p>
    <p align="center">
    <label>Сообщение для участников: {{ room.host_message }}<br></label>
  </p>
<h2>Список игроков:</h2>

{% for p in room.participants %}
<div>
  <h3>{{ p.username }}</h3>
  {% if current_user.id == room.host_id %}
  <a href="{{ url_for('matches.exclude_user', user_id=p.id, room_id=room.id) }}" class="button3">Исключить</a>
  {% endif %}
</div>
{% endfor %}

<a href="{{ url_for('matches.user_page') }}" class="button3">Назад</a>
</body>
</html>

app/templates/registration.html
<html>
<head>
<meta charset="utf-8">
<title>TNB-syte</title>
<link rel="stylesheet" type="text/css" href="../static/reg_style.css">
</head>
<center><h1>TNB-syte</h1></center>
<body>
  <p align="center">
    <label>Ник:<br></label>
    <input name="name" type="text" size="30" maxlength="30" value ="">
  </p>
  <p align="center">
    <label>E-mail:<br></label>
    <input name="name" type="text" size="30" maxlength="30" value ="">
  </p>
  <p align="center">
    <label>Пароль:<br></label>
    <input name="name" type="text" size="30" maxlength="30" value ="">
  </p>
 <a href="#" class="button2">Зарегистрироваться</a>
</body>
</html>

app/templates/usr_page.html
<html>
<head>
<meta charset="utf-8">
<title>TNB-syte</title>
<link rel="stylesheet" type="text/css" href="../static/usr_page_style.css">
</head>
<body/>
<a href="{{ url_for('main.home') }}" class="button1">На главную</a>
<a href="{{ url_for('matches.edit_match', room_id=0) }}" class="button2">Создать матч</a>
<h1>{{ current_user.username }}</h1>

<h2>Список матчей пользователя:</h2>

<h3>Список созданных матчей:</h3>


<div class="box1">
  {% for user_room in user_rooms %}
  <div class="title">
    {{ user_room.name }}
  </div>
  <div class="meaning">
    {{ user_room.game.name }}
  </div>
    <div class="button">
  	<a href="{{ url_for('matches.show_room', room_id=user_room.id) }}" class="button25">Подробнее</a>
	<a href="{{ url_for('matches.delete_room', room_id=user_room.id) }}" class="button24">Удалить</a>
	<a href="{{ url_for('matches.edit_match', room_id=user_room.id) }}" class="button24">Изменить</a>
	</div>
    {% endfor %}
</div>



<div class="box2">
  {% for room in rooms %}
  <div class="title">
    {{ room.name }}
  </div>
  <div class="meaning">
    {{ room.game.name }}
  </div>
    <div class="button">
  	<a href="{{ url_for('matches.show_room', room_id=room.id) }}" class="button25">Подробнее</a>
    <a href="{{ url_for('users.leave_room',room_id=room.id) }}" class="button24">Выйти</a>
	</div>
    {% endfor %}
</div>

</body>
</html>